/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/


#include <iostream>
#include <cassert>
#include <typeinfo>

namespace mpl_ {

	template <bool B> struct bool_;
	template <class I, I val> struct integral_c;
	struct integral_c_tag;
}

namespace mpl
{
	using ::mpl_::bool_;
	using ::mpl_::integral_c;
	using ::mpl_::integral_c_tag;
}


template <class T, T val>
struct integral_constant
{
	typedef mpl::integral_c_tag tag;
	typedef T value_type;
	typedef integral_constant<T, val> type;
	static const T value = val;

	operator const mpl::integral_c<T, val>& ()const
	{
		static const char data[sizeof(long)] = { 0 };
		static const void* pdata = data;
		return *(reinterpret_cast<const mpl::integral_c<T, val>*>(pdata));
	}
	constexpr operator T()const { return val; }
};

template <class T, T val>
T const integral_constant<T, val>::value;

template <bool val>
struct integral_constant<bool, val>
{
	typedef mpl::integral_c_tag tag;
	typedef bool value_type;
	typedef integral_constant<bool, val> type;
	static const bool value = val;

	operator const mpl::bool_<val>& ()const
	{
		static const char data[sizeof(long)] = { 0 };
		static const void* pdata = data;
		return *(reinterpret_cast<const mpl::bool_<val>*>(pdata));
	}
	constexpr operator bool()const { return val; }
};

template <bool val>
bool const integral_constant<bool, val>::value;

typedef integral_constant<bool, true> true_type;
typedef integral_constant<bool, false> false_type;




template <class T>
struct is_const : public false_type {};
template <class T> struct is_const<T const> : public true_type {};
template <class T, std::size_t N> struct is_const<T const[N]> : public true_type {};
template <class T> struct is_const<T const[]> : public true_type {};

int main()
{
	using std::cout;
	using std::endl;

	{
		is_const<int> isconstint;
		
		// false
		cout << isconstint.value << endl;
	}

	{
		is_const<const int> isconstint;

		// true
		cout << isconstint.value << endl;
	}

	{
		is_const<char *> charpconstint;

		// false
		cout << charpconstint.value << endl;
	}

	{
		is_const<const char *> ccharpconstint;

		// false
		cout << ccharpconstint.value << endl;
	}

	{
		is_const<char const*> charcpconstint;

		// false
		cout << charcpconstint.value << endl;
	}

	{
		is_const<const char *> charcpconstpint;

		// false
		cout << charcpconstpint.value << endl;
	}
	{
		is_const<const char * const> charcpconstpint;

		// true
		cout << charcpconstpint.value << endl;
	}

}

